---

- hosts: all
  tasks:
  - name: install updates & upgrades for APT
    tags: always
    apt:
      update_cache: yes
      upgrade: dist
    when: ansible_distribution in [ "Ubuntu", "Debian"]

  - name: install updates & upgrades for DNF
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution in [ "Fedora", "CentOS"]

- hosts: all
  become: true
  tasks:
  - name: Add User 'home'
    tags: always
    user:
      name: home
      groups: root

  - name: add SSH key to target
    tags: always
    authorized_key:
      user: home
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIxHqJTKqeaia0QXRzblTIstRNo2EYEuNCAavnHVHYx1 ansible"

  - name: add sudoers file for 'home' User
    tags: always
#    gather_facts: no
    copy:
      src: sudoer_home
      dest: /etc/sudoers.d/home
      owner: root
      group: root
      mode: 0440
    when: ansible_distribution in [ "Fedora", "CentOS"]

- hosts: laptop
  become: true
  tasks:
  - name: install Apache 2 Package with PHP support
    tags: apache, apache2, php, fedora, centos
    dnf:
      name:
        - httpd
        - php
      state: latest
#      update_cache: yes
#    ansible_user_ssh: "home"
#    set_fact:
#      remote_user: "{{ remote_user }}"
    when: ansible_distribution in [ "Fedora", "CentOS" ]

  - name: copy files/default-site.html file to target
    tags: apache, apache2, php, centos, fedora
    copy: 
      src: default-site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

  - name: start HTTPD service
    tags: apache, apache2, php, centos, fedora
    service: 
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution in [ "Fedora", "CentOS" ]

  - name: change e-mail address for admin
    tags: apache, apache2, php, httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: 'ServerAdmin'
      line: ServerAdmin admin@divinefarms.ma
    register: httpd

  - name: restart HTTPD service
    tags: apache, apache2, php, centos, fedora
    service: 
      name: httpd
      state: restarted
    when: httpd.changed

- hosts: rpi
  tasks:
  - name: install Apache 2 Package and PHP support
    tags: apache, apache2, php, debian, rpi, httpd
    apt:
      name:
      - apache2
      - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution in [ "Ubuntu", "Debian"]

  - name: copy files/default-site.html file to target
    tags: apache, apache2, php, httpd
    copy: 
      src: default-site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

  - name: change keepalive timeout on Apache2 server
    tags: apache, apache2, php, httpd
    lineinfile:
      path: /etc/apache2/apache2.conf
      regexp: '^KeepAliveTimeout'
      line: KeepAliveTimeout 8
    register: apache2

  - name: restart APACHE2 service
    tags: apache, apache2, php, centos, fedora
    service: 
      name: apache2
      state: restarted
    when: apache2.changed

- hosts: workstations
  tasks:
    - name: install Unzip
      package:
        name: unzip

    - name: install terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/1.5.4/terraform_1.5.4_linux_arm64.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: 0755
        owner: root
        group: root

- hosts: laptop
  become: true
  tags: centos, autoremove
  tasks:
  - name: Autoremove unneeded packages installed as dependencies
    ansible.builtin.dnf:
      autoremove: yes
