---

- hosts: all
  tasks:
  - name: apt update
    apt:
      update_cache: yes
  - name: install Apache 2 Package
    apt:
      name: apache2
      state: latest
  - name: install Apache 2 PHP support
    apt:
      name: libapache2-mod-php
      state: latest
